title: DIP-Based AI Image Detection
description: Feature-based AI image detection using DIP and MLP

remote_theme: just-the-docs/just-the-docs@v0.12.0
plugins:
  - jekyll-remote-theme

url: https://pgailinas.github.io
baseurl: /dip-ai-image-detection
